[package]
edition = "2018"

name = "slide"
version = "0.0.1"
authors = [ "Justin Miller <justinrmiller@gmail.com>" ]

[dependencies]
dashmap = "3.11.1"
rayon = "1.2.1"
fxhash = "0.2.1"
rand = "0.7.3"
evmap = "10.0.1"
ordered-float = "1.0"